services:

  fargo.api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fargo-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Server=fargo.sqlserver,1433;Database=FargoDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
      DefaultAdminNameid: admin
      DefaultAdminPassword: Admin123!
    ports:
      - "8080:8080"
    depends_on:
      - fargo.db

  fargo.web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: fargo-web
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      Api__BaseUrl: http://fargo.api:8080
    ports:
      - "8081:8081"
    depends_on:
      - fargo.api

  fargo.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fargo-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
