<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fargo.Application\Fargo.Application.csproj" />
    <ProjectReference Include="..\Fargo.Application.Shared\Fargo.Application.Shared.csproj" />
    <ProjectReference Include="..\Fargo.Core\Fargo.Core.csproj" />
  </ItemGroup>

</Project>
