@articleGuid = 4bc9b328-a6aa-4b7d-a5ba-a6c3925526c5
@itemGuid = d419a289-bb4a-47e0-a4c9-0d6e2a64b81b
@partitionGuid = 55555555-5555-5555-5555-555555555555

### Get

GET {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}

###

### List

GET {{host}}/items?page=1&limit=20
Authorization: Bearer {{jwt}}

###

### Create

POST {{host}}/items
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "articleGuid": "{{articleGuid}}"
}

###

### Update

PATCH {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "partitions": [
    "{{partitionGuid}}"
  ],
  "ParentItemContainerGuid": "0100ac3a-19cb-442b-9857-b5fb5da8cb6e"
}

###

### Delete

DELETE {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}