@articleGuid = 2a1d9d15-937d-4b2d-88ee-8f07ea865766
@itemGuid = 355ccc47-c20a-48b3-9a75-61ca12eac38d
@partitionGuid = 55555555-5555-5555-5555-555555555555

### Get

GET {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}

###

### List

GET {{host}}/items?page=1&limit=20
Authorization: Bearer {{jwt}}

###

### Create

POST {{host}}/items
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "articleGuid": "{{articleGuid}}"
}

###

### Update

PATCH {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "ParentItemContainerGuid": "e39e3218-ae4d-42d2-83ec-fe6dcff846ef"
}

###

### Delete

DELETE {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}