@userGuid = 89066e82-fe7a-4fba-8cc1-e656a24a0029
@partitionGuid = 55555555-5555-5555-5555-555555555555

### Get

GET {{host}}/users/{{userGuid}}
Authorization: Bearer {{jwt}}

###

### List

GET {{host}}/users?page=1&limit=20
Authorization: Bearer {{jwt}}

###

### Create

POST {{host}}/users
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "nameid": "igor5",
  "password": "Password123!",
  "firstName": "Igor",
  "lastName": "Doe",
  "description": "Test.",
  "partitionAccessesToAdd": ["00000000-0000-0000-0000-000000000002"]
}

###

### Update

PUT {{host}}/users/{{userGuid}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "description": "Updated user",
  "userGroupsToAdd": ["597b9765-79c9-4f51-941e-8e1d17244c9e"]
}

###

### Delete

DELETE {{host}}/users/{{userGuid}}
Authorization: Bearer {{jwt}}