@articleGuid = fdbd3eeb-f83e-4936-9960-c127bb8e82f7
@partitionGuid = 55555555-5555-5555-5555-555555555555

### Get by Guid

GET {{host}}/articles/{{articleGuid}}
Authorization: Bearer {{jwt}}

###

### Get by Barcode

GET {{host}}/articles/7891234567895:Ean13
Authorization: Bearer {{jwt}}

###

### List

GET {{host}}/articles?page=1&limit=20
Authorization: Bearer {{jwt}}

###

### Create

POST {{host}}/articles
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "item",
  "articleType": 2,
  "variation": {
    "fromArticleGuid": "cc4ad0a8-fa25-417a-9fff-52a9126cd0d3"
  },
  "barcode": {
    //"ean13": "1234567891234"
  }
}

###

### Patch

PATCH {{host}}/articles/{{articleGuid}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "description": "Updated description",
  "barcode":{
    //"ean13": "9876543211231"
    "removeEan13": true
  }
}

###

### Delete

DELETE {{host}}/articles/{{articleGuid}}
Authorization: Bearer {{jwt}}