@articleGuid = 68300812-fc24-4a0a-a9d5-f13ca7754016
@itemGuid = 4a5109f6-a603-4c31-a751-7a0a504b772d
@partitionGuid = 55555555-5555-5555-5555-555555555555

### Get

GET {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}

###

### Get location

GET {{host}}/items/{{itemGuid}}/location
Authorization: Bearer {{jwt}}

###

### Get moviments

GET {{host}}/items/{{itemGuid}}/moviments
Authorization: Bearer {{jwt}}

###

### List

GET {{host}}/items?page=1&limit=20
Authorization: Bearer {{jwt}}

###

### Create

POST {{host}}/items
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "articleGuid": "{{articleGuid}}"
}

###

### Update

PATCH {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "ParentItemContainerGuid": "64906ad6-bad4-4338-a533-8fd48542913f"
  //"RemoveFromParentItemContainer": true
}

###

### Delete

DELETE {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}