@articleGuid = f5269e5c-b65e-481b-842a-38fc0cef448c
@itemGuid = 567ad575-76f2-4d2a-8c7d-563f4416cbf7
@partitionGuid = 55555555-5555-5555-5555-555555555555

### Get

GET {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}

###

### List

GET {{host}}/items?page=1&limit=20
Authorization: Bearer {{jwt}}

###

### Create

POST {{host}}/items
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "articleGuid": "{{articleGuid}}"
}

###

### Update

PATCH {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  //"ParentItemContainerGuid": "840ec76c-58e1-4031-95fa-005e9e7c78bb"
  "RemoveFromParentItemContainer": true
}

###

### Delete

DELETE {{host}}/items/{{itemGuid}}
Authorization: Bearer {{jwt}}