@userGuid = bd5c6af7-e94b-46a2-8506-bf736857f248
@partitionGuid = 55555555-5555-5555-5555-555555555555

### Get

GET {{host}}/users/{{userGuid}}
Authorization: Bearer {{jwt}}

###

### List

GET {{host}}/users?page=1&limit=20
Authorization: Bearer {{jwt}}

###

### Create

POST {{host}}/users
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "nameid": "igor7",
  "authentication": { "password": "Password123!" },
  "firstName": "Igor",
  "lastName": "Doe",
  "description": "Test.",
  "userGroupsToAdd": ["597b9765-79c9-4f51-941e-8e1d17244c9e"]
}

###

### Update

PUT {{host}}/users/{{userGuid}}
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "description": "Updated user",
  "userGroupsToAdd": ["597b9765-79c9-4f51-941e-8e1d17244c9e"]
}

###

### Delete

DELETE {{host}}/users/{{userGuid}}
Authorization: Bearer {{jwt}}