// <auto-generated />
using System;
using Fargo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fargo.Infrastructure.Migrations
{
    [DbContext(typeof(FargoDbContext))]
    [Migration("20260810195021_ItemIsFixedColumn")]
    partial class ItemIsFixedColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fargo.Core.Articles.Article", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<byte>("ArticleType")
                        .HasColumnType("smallint")
                        .HasColumnName("article_type");

                    b.Property<int?>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Mass")
                        .HasColumnType("text")
                        .HasColumnName("mass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long?>("ShelfLife")
                        .HasColumnType("bigint")
                        .HasColumnName("shelf_life");

                    b.HasKey("Guid")
                        .HasName("pk_articles");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleBarcode", b =>
                {
                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.Property<string>("Ean13")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ean13");

                    b.HasKey("ArticleGuid")
                        .HasName("pk_article_barcodes");

                    b.HasIndex("Ean13")
                        .IsUnique()
                        .HasDatabaseName("ix_article_barcodes_ean13")
                        .HasFilter("ean13 IS NOT NULL");

                    b.ToTable("article_barcodes", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleContainer", b =>
                {
                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.Property<string>("MaxMass")
                        .HasColumnType("text")
                        .HasColumnName("max_mass");

                    b.HasKey("ArticleGuid")
                        .HasName("pk_article_containers");

                    b.ToTable("article_containers", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleDimension", b =>
                {
                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.Property<string>("X")
                        .HasColumnType("text")
                        .HasColumnName("x");

                    b.Property<string>("Y")
                        .HasColumnType("text")
                        .HasColumnName("y");

                    b.Property<string>("Z")
                        .HasColumnType("text")
                        .HasColumnName("z");

                    b.HasKey("ArticleGuid")
                        .HasName("pk_article_dimensions");

                    b.ToTable("article_dimensions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKitComponent", b =>
                {
                    b.Property<Guid>("KitArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("kit_article_guid");

                    b.Property<Guid>("FromArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("from_article_guid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("KitArticleGuid")
                        .HasName("pk_article_kit_components");

                    b.HasIndex("FromArticleGuid")
                        .HasDatabaseName("ix_article_kit_components_from_article_guid");

                    b.ToTable("article_kit_components", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticlePack", b =>
                {
                    b.Property<Guid>("PackArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_article_guid");

                    b.Property<Guid>("FromArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("from_article_guid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("PackArticleGuid")
                        .HasName("pk_article_packs");

                    b.HasIndex("FromArticleGuid")
                        .HasDatabaseName("ix_article_packs_from_article_guid");

                    b.ToTable("article_packs", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticlePartition", b =>
                {
                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.Property<Guid>("PartitionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partition_guid");

                    b.HasKey("ArticleGuid", "PartitionGuid")
                        .HasName("pk_article_partitions");

                    b.HasIndex("PartitionGuid")
                        .HasDatabaseName("ix_article_partitions_partition_guid");

                    b.ToTable("article_partitions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleVariation", b =>
                {
                    b.Property<Guid>("VariationArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_article_guid");

                    b.Property<Guid>("FromArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("from_article_guid");

                    b.HasKey("VariationArticleGuid")
                        .HasName("pk_article_variations");

                    b.HasIndex("FromArticleGuid")
                        .HasDatabaseName("ix_article_variations_from_article_guid");

                    b.ToTable("article_variations", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Audits.AuditLog", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<Guid>("ActorGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_guid");

                    b.Property<byte>("ActorType")
                        .HasColumnType("smallint")
                        .HasColumnName("actor_type");

                    b.Property<Guid>("EntityGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_guid");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Guid")
                        .HasName("pk_audit_logs");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_logs_occurred_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.HasKey("Guid")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserGuid")
                        .HasDatabaseName("ix_refresh_tokens_user_guid");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fixed");

                    b.Property<Guid?>("ParentItemContainerGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_item_container_guid");

                    b.HasKey("Guid")
                        .HasName("pk_items");

                    b.HasIndex("ArticleGuid")
                        .HasDatabaseName("ix_items_article_guid");

                    b.HasIndex("ParentItemContainerGuid")
                        .HasDatabaseName("ix_items_parent_item_container_guid");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Items.ItemPartition", b =>
                {
                    b.Property<Guid>("ItemGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("item_guid");

                    b.Property<Guid>("PartitionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partition_guid");

                    b.HasKey("ItemGuid", "PartitionGuid")
                        .HasName("pk_item_partitions");

                    b.HasIndex("PartitionGuid")
                        .HasDatabaseName("ix_item_partitions_partition_guid");

                    b.ToTable("item_partitions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentPartitionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_partition_guid");

                    b.HasKey("Guid")
                        .HasName("pk_partitions");

                    b.HasIndex("ParentPartitionGuid")
                        .HasDatabaseName("ix_partitions_parent_partition_guid");

                    b.ToTable("partitions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Nameid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nameid");

                    b.Property<Guid?>("ParentUserGroupGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_user_group_guid");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.HasKey("Guid")
                        .HasName("pk_user_groups");

                    b.HasIndex("Nameid")
                        .IsUnique()
                        .HasDatabaseName("ix_user_groups_nameid");

                    b.HasIndex("ParentUserGroupGuid")
                        .HasDatabaseName("ix_user_groups_parent_user_group_guid");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPartition", b =>
                {
                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_guid");

                    b.Property<Guid>("PartitionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partition_guid");

                    b.HasKey("UserGroupGuid", "PartitionGuid")
                        .HasName("pk_user_group_partitions");

                    b.HasIndex("PartitionGuid")
                        .HasDatabaseName("ix_user_group_partitions_partition_guid");

                    b.ToTable("user_group_partitions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPartitionAccess", b =>
                {
                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_guid");

                    b.Property<Guid>("PartitionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partition_guid");

                    b.HasKey("UserGroupGuid", "PartitionGuid")
                        .HasName("pk_user_group_partition_accesses");

                    b.HasIndex("PartitionGuid")
                        .HasDatabaseName("ix_user_group_partition_accesses_partition_guid");

                    b.ToTable("user_group_partition_accesses", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Users.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nameid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nameid");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.HasKey("Guid")
                        .HasName("pk_users");

                    b.HasIndex("Nameid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_nameid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Users.UserAuthentication", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.Property<Guid>("AuthVersion")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_version");

                    b.Property<long?>("DefaultPasswordExpirationPeriod")
                        .HasColumnType("bigint")
                        .HasColumnName("default_password_expiration_period");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("RequirePasswordChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("require_password_change_at");

                    b.HasKey("UserGuid")
                        .HasName("pk_user_authentications");

                    b.ToTable("user_authentications", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Users.UserPartition", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.Property<Guid>("PartitionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partition_guid");

                    b.HasKey("UserGuid", "PartitionGuid")
                        .HasName("pk_user_partitions");

                    b.HasIndex("PartitionGuid")
                        .HasDatabaseName("ix_user_partitions_partition_guid");

                    b.ToTable("user_partitions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Users.UserPartitionAccess", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.Property<Guid>("PartitionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partition_guid");

                    b.HasKey("UserGuid", "PartitionGuid")
                        .HasName("pk_user_partition_accesses");

                    b.HasIndex("PartitionGuid")
                        .HasDatabaseName("ix_user_partition_accesses_partition_guid");

                    b.ToTable("user_partition_accesses", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Users.UserUserGroup", b =>
                {
                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_guid");

                    b.HasKey("UserGuid", "UserGroupGuid")
                        .HasName("pk_user_user_groups");

                    b.HasIndex("UserGroupGuid")
                        .HasDatabaseName("ix_user_user_groups_user_group_guid");

                    b.ToTable("user_user_groups", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleBarcode", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithOne("Barcode")
                        .HasForeignKey("Fargo.Core.Articles.ArticleBarcode", "ArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_barcodes_articles_article_guid");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleContainer", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithOne("Container")
                        .HasForeignKey("Fargo.Core.Articles.ArticleContainer", "ArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_containers_articles_article_guid");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleDimension", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithOne("Dimension")
                        .HasForeignKey("Fargo.Core.Articles.ArticleDimension", "ArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_dimensions_articles_article_guid");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKitComponent", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                        .WithMany()
                        .HasForeignKey("FromArticleGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_kit_components_articles_from_article_guid");

                    b.HasOne("Fargo.Core.Articles.Article", "KitArticle")
                        .WithMany("KitComponents")
                        .HasForeignKey("KitArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_kit_components_articles_kit_article_guid");

                    b.Navigation("FromArticle");

                    b.Navigation("KitArticle");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticlePack", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                        .WithMany()
                        .HasForeignKey("FromArticleGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_packs_articles_from_article_guid");

                    b.HasOne("Fargo.Core.Articles.Article", "PackArticle")
                        .WithOne("Pack")
                        .HasForeignKey("Fargo.Core.Articles.ArticlePack", "PackArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_packs_articles_pack_article_guid");

                    b.Navigation("FromArticle");

                    b.Navigation("PackArticle");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticlePartition", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithMany("Partitions")
                        .HasForeignKey("ArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_partitions_articles_article_guid");

                    b.HasOne("Fargo.Core.Partitions.Partition", "Partition")
                        .WithMany()
                        .HasForeignKey("PartitionGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_partitions_partitions_partition_guid");

                    b.Navigation("Article");

                    b.Navigation("Partition");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleVariation", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                        .WithMany()
                        .HasForeignKey("FromArticleGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_article_variations_articles_from_article_guid");

                    b.HasOne("Fargo.Core.Articles.Article", "VariationArticle")
                        .WithOne("Variation")
                        .HasForeignKey("Fargo.Core.Articles.ArticleVariation", "VariationArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_variations_articles_variation_article_guid");

                    b.Navigation("FromArticle");

                    b.Navigation("VariationArticle");
                });

            modelBuilder.Entity("Fargo.Core.Identity.RefreshToken", b =>
                {
                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_guid");
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_articles_article_guid");

                    b.HasOne("Fargo.Core.Items.Item", "ParentItemContainer")
                        .WithMany()
                        .HasForeignKey("ParentItemContainerGuid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_items_items_parent_item_container_guid");

                    b.Navigation("Article");

                    b.Navigation("ParentItemContainer");
                });

            modelBuilder.Entity("Fargo.Core.Items.ItemPartition", b =>
                {
                    b.HasOne("Fargo.Core.Items.Item", "Item")
                        .WithMany("Partitions")
                        .HasForeignKey("ItemGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_partitions_items_item_guid");

                    b.HasOne("Fargo.Core.Partitions.Partition", "Partition")
                        .WithMany()
                        .HasForeignKey("PartitionGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_partitions_partitions_partition_guid");

                    b.Navigation("Item");

                    b.Navigation("Partition");
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "ParentPartition")
                        .WithMany()
                        .HasForeignKey("ParentPartitionGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_partitions_partitions_parent_partition_guid");

                    b.Navigation("ParentPartition");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.HasOne("Fargo.Core.UserGroups.UserGroup", "ParentUserGroup")
                        .WithMany()
                        .HasForeignKey("ParentUserGroupGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_groups_user_groups_parent_user_group_guid");

                    b.Navigation("ParentUserGroup");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPartition", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "Partition")
                        .WithMany()
                        .HasForeignKey("PartitionGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_partitions_partitions_partition_guid");

                    b.HasOne("Fargo.Core.UserGroups.UserGroup", "UserGroup")
                        .WithMany("Partitions")
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_partitions_user_groups_user_group_guid");

                    b.Navigation("Partition");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPartitionAccess", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "Partition")
                        .WithMany()
                        .HasForeignKey("PartitionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_partition_accesses_partitions_partition_guid");

                    b.HasOne("Fargo.Core.UserGroups.UserGroup", "UserGroup")
                        .WithMany("PartitionAccesses")
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_group_partition_accesses_user_groups_user_group_guid");

                    b.Navigation("Partition");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Fargo.Core.Users.UserAuthentication", b =>
                {
                    b.HasOne("Fargo.Core.Users.User", "User")
                        .WithOne("Authentication")
                        .HasForeignKey("Fargo.Core.Users.UserAuthentication", "UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_authentications_users_user_guid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fargo.Core.Users.UserPartition", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "Partition")
                        .WithMany()
                        .HasForeignKey("PartitionGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_partitions_partitions_partition_guid");

                    b.HasOne("Fargo.Core.Users.User", "User")
                        .WithMany("Partitions")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_partitions_users_user_guid");

                    b.Navigation("Partition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fargo.Core.Users.UserPartitionAccess", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "Partition")
                        .WithMany()
                        .HasForeignKey("PartitionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_partition_accesses_partitions_partition_guid");

                    b.HasOne("Fargo.Core.Users.User", "User")
                        .WithMany("PartitionAccesses")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_partition_accesses_users_user_guid");

                    b.Navigation("Partition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fargo.Core.Users.UserUserGroup", b =>
                {
                    b.HasOne("Fargo.Core.UserGroups.UserGroup", "UserGroup")
                        .WithMany()
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_groups_user_groups_user_group_guid");

                    b.HasOne("Fargo.Core.Users.User", "User")
                        .WithMany("UserGroupMemberships")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_groups_users_user_guid");

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Fargo.Core.Articles.Article", b =>
                {
                    b.Navigation("Barcode")
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("Dimension")
                        .IsRequired();

                    b.Navigation("KitComponents");

                    b.Navigation("Pack");

                    b.Navigation("Partitions");

                    b.Navigation("Variation");
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.Navigation("Partitions");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.Navigation("PartitionAccesses");

                    b.Navigation("Partitions");
                });

            modelBuilder.Entity("Fargo.Core.Users.User", b =>
                {
                    b.Navigation("Authentication")
                        .IsRequired();

                    b.Navigation("PartitionAccesses");

                    b.Navigation("Partitions");

                    b.Navigation("UserGroupMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
