// <auto-generated />
using System;
using Fargo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fargo.Infrastructure.Migrations
{
    [DbContext(typeof(FargoDbContext))]
    [Migration("20260801230723_UserKitPackVariationKeyRefact")]
    partial class UserKitPackVariationKeyRefact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticlePartition", b =>
                {
                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partitions_guid");

                    b.HasKey("ArticleGuid", "PartitionsGuid")
                        .HasName("pk_article_partition");

                    b.HasIndex("PartitionsGuid")
                        .HasDatabaseName("ix_article_partition_partitions_guid");

                    b.ToTable("article_partition", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.Article", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<int>("ArticleType")
                        .HasColumnType("integer")
                        .HasColumnName("article_type");

                    b.Property<string>("Code128")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code128");

                    b.Property<string>("Code39")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code39");

                    b.Property<int?>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<string>("DataMatrix")
                        .HasMaxLength(2335)
                        .HasColumnType("character varying(2335)")
                        .HasColumnName("data_matrix");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Ean13")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ean13");

                    b.Property<string>("Ean8")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ean8");

                    b.Property<string>("Gs1128")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("gs1128");

                    b.Property<string>("Itf14")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("itf14");

                    b.Property<string>("LengthX")
                        .HasColumnType("text")
                        .HasColumnName("length_x");

                    b.Property<string>("LengthY")
                        .HasColumnType("text")
                        .HasColumnName("length_y");

                    b.Property<string>("LengthZ")
                        .HasColumnType("text")
                        .HasColumnName("length_z");

                    b.Property<string>("Mass")
                        .HasColumnType("text")
                        .HasColumnName("mass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("QrCode")
                        .HasMaxLength(2953)
                        .HasColumnType("character varying(2953)")
                        .HasColumnName("qr_code");

                    b.Property<long?>("ShelfLife")
                        .HasColumnType("bigint")
                        .HasColumnName("shelf_life");

                    b.Property<string>("UpcA")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("upc_a");

                    b.Property<string>("UpcE")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("upc_e");

                    b.HasKey("Guid")
                        .HasName("pk_articles");

                    b.HasIndex("Code128")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_code128")
                        .HasFilter("code128 IS NOT NULL");

                    b.HasIndex("Code39")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_code39")
                        .HasFilter("code39 IS NOT NULL");

                    b.HasIndex("DataMatrix")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_data_matrix")
                        .HasFilter("data_matrix IS NOT NULL");

                    b.HasIndex("Ean13")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_ean13")
                        .HasFilter("ean13 IS NOT NULL");

                    b.HasIndex("Ean8")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_ean8")
                        .HasFilter("ean8 IS NOT NULL");

                    b.HasIndex("Gs1128")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_gs1128")
                        .HasFilter("gs1128 IS NOT NULL");

                    b.HasIndex("Itf14")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_itf14")
                        .HasFilter("itf14 IS NOT NULL");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_qr_code")
                        .HasFilter("qr_code IS NOT NULL");

                    b.HasIndex("UpcA")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_upc_a")
                        .HasFilter("upc_a IS NOT NULL");

                    b.HasIndex("UpcE")
                        .IsUnique()
                        .HasDatabaseName("ix_articles_upc_e")
                        .HasFilter("upc_e IS NOT NULL");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleContainer", b =>
                {
                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.Property<string>("MaxMass")
                        .HasColumnType("text")
                        .HasColumnName("max_mass");

                    b.HasKey("ArticleGuid")
                        .HasName("pk_article_containers");

                    b.ToTable("article_containers", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKit", b =>
                {
                    b.Property<Guid>("KitArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("kit_article_guid");

                    b.HasKey("KitArticleGuid")
                        .HasName("pk_article_kits");

                    b.ToTable("article_kits", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKitComponent", b =>
                {
                    b.Property<Guid>("KitArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("kit_article_guid");

                    b.Property<Guid>("FromArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("from_article_guid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("KitArticleGuid")
                        .HasName("pk_article_kit_components");

                    b.HasIndex("FromArticleGuid")
                        .HasDatabaseName("ix_article_kit_components_from_article_guid");

                    b.ToTable("article_kit_components", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticlePack", b =>
                {
                    b.Property<Guid>("PackArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_article_guid");

                    b.Property<Guid>("FromArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("from_article_guid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.HasKey("PackArticleGuid")
                        .HasName("pk_article_packs");

                    b.HasIndex("FromArticleGuid")
                        .HasDatabaseName("ix_article_packs_from_article_guid");

                    b.ToTable("article_packs", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleVariation", b =>
                {
                    b.Property<Guid>("VariationArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("variation_article_guid");

                    b.Property<Guid>("FromArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("from_article_guid");

                    b.HasKey("VariationArticleGuid")
                        .HasName("pk_article_variations");

                    b.HasIndex("FromArticleGuid")
                        .HasDatabaseName("ix_article_variations_from_article_guid");

                    b.ToTable("article_variations", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.HasKey("Guid")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserGuid")
                        .HasDatabaseName("ix_refresh_tokens_user_guid");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.Property<Guid?>("ParentContainerGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_container_guid");

                    b.Property<DateTimeOffset?>("ProductionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("production_date");

                    b.Property<Guid?>("article_guid")
                        .HasColumnType("uuid")
                        .HasColumnName("article_guid");

                    b.HasKey("Guid")
                        .HasName("pk_items");

                    b.HasIndex("ArticleGuid")
                        .HasDatabaseName("ix_items_article_guid");

                    b.HasIndex("ParentContainerGuid")
                        .HasDatabaseName("ix_items_parent_container_guid");

                    b.HasIndex("article_guid")
                        .IsUnique()
                        .HasDatabaseName("ix_items_article_guid1");

                    b.ToTable("items", null, t =>
                        {
                            t.Property("article_guid")
                                .HasColumnName("article_guid1");
                        });
                });

            modelBuilder.Entity("Fargo.Core.Items.ItemContainer", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.HasKey("Guid")
                        .HasName("pk_item_containers");

                    b.ToTable("item_containers", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentPartitionGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_partition_guid");

                    b.Property<Guid?>("UserGroupGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_guid");

                    b.HasKey("Guid")
                        .HasName("pk_partitions");

                    b.HasIndex("ParentPartitionGuid")
                        .HasDatabaseName("ix_partitions_parent_partition_guid");

                    b.HasIndex("UserGroupGuid")
                        .HasDatabaseName("ix_partitions_user_group_guid");

                    b.ToTable("partitions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Nameid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nameid");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.HasKey("Guid")
                        .HasName("pk_user_groups");

                    b.HasIndex("Nameid")
                        .IsUnique()
                        .HasDatabaseName("ix_user_groups_nameid");

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Users.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<Guid>("AuthVersion")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_version");

                    b.Property<long?>("DefaultPasswordExpirationPeriod")
                        .HasColumnType("bigint")
                        .HasColumnName("default_password_expiration_period");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nameid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nameid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.PrimitiveCollection<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<DateTimeOffset?>("RequirePasswordChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("require_password_change_at");

                    b.HasKey("Guid")
                        .HasName("pk_users");

                    b.HasIndex("Nameid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_nameid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ItemPartition", b =>
                {
                    b.Property<Guid>("ItemGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("item_guid");

                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partitions_guid");

                    b.HasKey("ItemGuid", "PartitionsGuid")
                        .HasName("pk_item_partition");

                    b.HasIndex("PartitionsGuid")
                        .HasDatabaseName("ix_item_partition_partitions_guid");

                    b.ToTable("item_partition", (string)null);
                });

            modelBuilder.Entity("PartitionUser", b =>
                {
                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partitions_guid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.HasKey("PartitionsGuid", "UserGuid")
                        .HasName("pk_partition_user");

                    b.HasIndex("UserGuid")
                        .HasDatabaseName("ix_partition_user_user_guid");

                    b.ToTable("partition_user", (string)null);
                });

            modelBuilder.Entity("PartitionUser1", b =>
                {
                    b.Property<Guid>("PartitionAccessesGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partition_accesses_guid");

                    b.Property<Guid>("User1Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("user1guid");

                    b.HasKey("PartitionAccessesGuid", "User1Guid")
                        .HasName("pk_partition_user1");

                    b.HasIndex("User1Guid")
                        .HasDatabaseName("ix_partition_user1_user1guid");

                    b.ToTable("partition_user1", (string)null);
                });

            modelBuilder.Entity("PartitionUserGroup", b =>
                {
                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("partitions_guid");

                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_group_guid");

                    b.HasKey("PartitionsGuid", "UserGroupGuid")
                        .HasName("pk_partition_user_group");

                    b.HasIndex("UserGroupGuid")
                        .HasDatabaseName("ix_partition_user_group_user_group_guid");

                    b.ToTable("partition_user_group", (string)null);
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.Property<Guid>("UserGroupsGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_groups_guid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_guid");

                    b.HasKey("UserGroupsGuid", "UserGuid")
                        .HasName("pk_user_user_group");

                    b.HasIndex("UserGuid")
                        .HasDatabaseName("ix_user_user_group_user_guid");

                    b.ToTable("user_user_group", (string)null);
                });

            modelBuilder.Entity("ArticlePartition", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_partition_articles_article_guid");

                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_partition_partitions_partitions_guid");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleContainer", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithOne("Container")
                        .HasForeignKey("Fargo.Core.Articles.ArticleContainer", "ArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_containers_articles_article_guid");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKit", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "KitArticle")
                        .WithOne("Kit")
                        .HasForeignKey("Fargo.Core.Articles.ArticleKit", "KitArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_kits_articles_kit_article_guid");

                    b.Navigation("KitArticle");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKitComponent", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                        .WithMany()
                        .HasForeignKey("FromArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_kit_components_articles_from_article_guid");

                    b.HasOne("Fargo.Core.Articles.ArticleKit", "Kit")
                        .WithMany("Components")
                        .HasForeignKey("KitArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_kit_components_article_kits_kit_article_guid");

                    b.Navigation("FromArticle");

                    b.Navigation("Kit");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticlePack", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                        .WithMany()
                        .HasForeignKey("FromArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_packs_articles_from_article_guid");

                    b.HasOne("Fargo.Core.Articles.Article", "PackArticle")
                        .WithOne("Pack")
                        .HasForeignKey("Fargo.Core.Articles.ArticlePack", "PackArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_packs_articles_pack_article_guid");

                    b.Navigation("FromArticle");

                    b.Navigation("PackArticle");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleVariation", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                        .WithMany()
                        .HasForeignKey("FromArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_variations_articles_from_article_guid");

                    b.HasOne("Fargo.Core.Articles.Article", "VariationArticle")
                        .WithOne("Variation")
                        .HasForeignKey("Fargo.Core.Articles.ArticleVariation", "VariationArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_variations_articles_variation_article_guid");

                    b.Navigation("FromArticle");

                    b.Navigation("VariationArticle");
                });

            modelBuilder.Entity("Fargo.Core.Identity.RefreshToken", b =>
                {
                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_guid");
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_articles_article_guid");

                    b.HasOne("Fargo.Core.Items.Item", "ParentContainer")
                        .WithMany()
                        .HasForeignKey("ParentContainerGuid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_items_items_parent_container_guid");

                    b.HasOne("Fargo.Core.Items.ItemContainer", "Container")
                        .WithOne()
                        .HasForeignKey("Fargo.Core.Items.Item", "article_guid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_items_item_containers_article_guid");

                    b.Navigation("Article");

                    b.Navigation("Container");

                    b.Navigation("ParentContainer");
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "ParentPartition")
                        .WithMany()
                        .HasForeignKey("ParentPartitionGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_partitions_partitions_parent_partition_guid");

                    b.HasOne("Fargo.Core.UserGroups.UserGroup", null)
                        .WithMany("PartitionAccesses")
                        .HasForeignKey("UserGroupGuid")
                        .HasConstraintName("fk_partitions_user_groups_user_group_guid");

                    b.Navigation("ParentPartition");
                });

            modelBuilder.Entity("ItemPartition", b =>
                {
                    b.HasOne("Fargo.Core.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_partition_items_item_guid");

                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_partition_partitions_partitions_guid");
                });

            modelBuilder.Entity("PartitionUser", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partition_user_partitions_partitions_guid");

                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partition_user_users_user_guid");
                });

            modelBuilder.Entity("PartitionUser1", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionAccessesGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partition_user1_partitions_partition_accesses_guid");

                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("User1Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partition_user1_users_user1guid");
                });

            modelBuilder.Entity("PartitionUserGroup", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partition_user_group_partitions_partitions_guid");

                    b.HasOne("Fargo.Core.UserGroups.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_partition_user_group_user_groups_user_group_guid");
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.HasOne("Fargo.Core.UserGroups.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_group_user_groups_user_groups_guid");

                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_user_group_users_user_guid");
                });

            modelBuilder.Entity("Fargo.Core.Articles.Article", b =>
                {
                    b.Navigation("Container");

                    b.Navigation("Kit");

                    b.Navigation("Pack");

                    b.Navigation("Variation");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKit", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.Navigation("PartitionAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
