// <auto-generated />
using System;
using Fargo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fargo.Infrastructure.Migrations;

[DbContext(typeof(FargoWriteDbContext))]
partial class FargoWriteDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Fargo.Domain.Entities.Article", b =>
            {
                b.Property<Guid>("Guid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime>("PeriodEnd")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasColumnName("PeriodEnd");

                b.Property<DateTime>("PeriodStart")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasColumnName("PeriodStart");

                b.HasKey("Guid");

                b.ToTable("Articles");

                b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb.UseHistoryTable("ArticlesHistory");
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }));
            });

        modelBuilder.Entity("Fargo.Domain.Entities.Item", b =>
            {
                b.Property<Guid>("Guid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ArticleGuid")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("PeriodEnd")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasColumnName("PeriodEnd");

                b.Property<DateTime>("PeriodStart")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasColumnName("PeriodStart");

                b.HasKey("Guid");

                b.HasIndex("ArticleGuid");

                b.ToTable("Items");

                b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb.UseHistoryTable("ItemsHistory");
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }));
            });

        modelBuilder.Entity("Fargo.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Guid")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Nameid")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("nvarchar(512)");

                b.Property<DateTime>("PeriodEnd")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasColumnName("PeriodEnd");

                b.Property<DateTime>("PeriodStart")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasColumnName("PeriodStart");

                b.HasKey("Guid");

                b.HasAlternateKey("Nameid");

                b.ToTable("Users");

                b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb.UseHistoryTable("UsersHistory");
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }));
            });

        modelBuilder.Entity("Fargo.Domain.Entities.UserPermission", b =>
            {
                b.Property<Guid>("UserGuid")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Action")
                    .HasColumnType("int");

                b.Property<DateTime>("PeriodEnd")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasColumnName("PeriodEnd");

                b.Property<DateTime>("PeriodStart")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("datetime2")
                    .HasColumnName("PeriodStart");

                b.HasKey("UserGuid", "Action");

                b.ToTable("UserPermission");

                b.ToTable(tb => tb.IsTemporal(ttb =>
                        {
                            ttb.UseHistoryTable("UserPermissionHistory");
                            ttb
                                .HasPeriodStart("PeriodStart")
                                .HasColumnName("PeriodStart");
                            ttb
                                .HasPeriodEnd("PeriodEnd")
                                .HasColumnName("PeriodEnd");
                        }));
            });

        modelBuilder.Entity("Fargo.Domain.Entities.Item", b =>
            {
                b.HasOne("Fargo.Domain.Entities.Article", "Article")
                    .WithMany()
                    .HasForeignKey("ArticleGuid")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Article");
            });

        modelBuilder.Entity("Fargo.Domain.Entities.UserPermission", b =>
            {
                b.HasOne("Fargo.Domain.Entities.User", "User")
                    .WithMany("UserPermissions")
                    .HasForeignKey("UserGuid")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Fargo.Domain.Entities.User", b =>
            {
                b.Navigation("UserPermissions");
            });
#pragma warning restore 612, 618
    }
}