// <auto-generated />
using System;
using Fargo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fargo.Infrastructure.Migrations
{
    [DbContext(typeof(FargoDbContext))]
    partial class FargoWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticlePartition", b =>
                {
                    b.Property<Guid>("ArticleMembersGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("ArticleMembersGuid", "PartitionsGuid");

                    b.HasIndex("PartitionsGuid");

                    b.ToTable("ArticlePartition");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ArticlePartitionHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.Articles.Article", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code128")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Code39")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("Color")
                        .HasColumnType("int");

                    b.Property<string>("DataMatrix")
                        .HasMaxLength(2335)
                        .HasColumnType("nvarchar(2335)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ean13")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Ean8")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Gs1128")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Itf14")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("LengthX")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LengthX");

                    b.Property<string>("LengthY")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LengthY");

                    b.Property<string>("LengthZ")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LengthZ");

                    b.Property<string>("Mass")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Mass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("QrCode")
                        .HasMaxLength(2953)
                        .HasColumnType("nvarchar(2953)");

                    b.Property<long?>("ShelfLife")
                        .HasColumnType("bigint");

                    b.Property<string>("UpcA")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("UpcE")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Guid");

                    b.HasIndex("Code128")
                        .IsUnique()
                        .HasFilter("[Code128] IS NOT NULL");

                    b.HasIndex("Code39")
                        .IsUnique()
                        .HasFilter("[Code39] IS NOT NULL");

                    b.HasIndex("DataMatrix")
                        .IsUnique()
                        .HasFilter("[DataMatrix] IS NOT NULL");

                    b.HasIndex("Ean13")
                        .IsUnique()
                        .HasFilter("[Ean13] IS NOT NULL");

                    b.HasIndex("Ean8")
                        .IsUnique()
                        .HasFilter("[Ean8] IS NOT NULL");

                    b.HasIndex("Gs1128")
                        .IsUnique()
                        .HasFilter("[Gs1128] IS NOT NULL");

                    b.HasIndex("Itf14")
                        .IsUnique()
                        .HasFilter("[Itf14] IS NOT NULL");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasFilter("[QrCode] IS NOT NULL");

                    b.HasIndex("UpcA")
                        .IsUnique()
                        .HasFilter("[UpcA] IS NOT NULL");

                    b.HasIndex("UpcE")
                        .IsUnique()
                        .HasFilter("[UpcE] IS NOT NULL");

                    b.ToTable("Articles", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ArticlesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserGuid");

                    b.ToTable("RefreshTokens");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("RefreshTokensHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("ParentContainerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<DateTimeOffset?>("ProductionDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Guid");

                    b.HasIndex("ArticleGuid");

                    b.HasIndex("ParentContainerGuid");

                    b.ToTable("Items");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ItemsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.Items.ItemContainer", b =>
                {
                    b.Property<Guid>("ItemGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("ItemGuid");

                    b.ToTable("ItemContainers", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ItemContainersHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentPartitionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Guid");

                    b.HasIndex("ParentPartitionGuid");

                    b.ToTable("Partitions");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("PartitionsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nameid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("Guid");

                    b.HasIndex("Nameid")
                        .IsUnique();

                    b.ToTable("UserGroups", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserGroupsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPartitionAccess", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartitionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("PartitionGuid");

                    b.HasIndex("UserGroupGuid");

                    b.ToTable("UserGroupPartitionAccesses", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserGroupPartitionAccessesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPermission", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasAlternateKey("UserGroupGuid", "Action");

                    b.ToTable("UserGroupPermissions", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserGroupPermissionsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.Users.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<long?>("DefaultPasswordExpirationPeriod")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nameid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<DateTimeOffset?>("RequirePasswordChangeAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Guid");

                    b.HasIndex("Nameid")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UsersHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.Users.UserPartitionAccess", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartitionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("PartitionGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserPartitionAccesses", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserPartitionAccessesHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("Fargo.Core.Users.UserPermission", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasAlternateKey("UserGuid", "Action");

                    b.ToTable("UserPermission");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserPermissionHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("ItemPartition", b =>
                {
                    b.Property<Guid>("ItemMembersGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("ItemMembersGuid", "PartitionsGuid");

                    b.HasIndex("PartitionsGuid");

                    b.ToTable("ItemPartition");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ItemPartitionHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("PartitionUser", b =>
                {
                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserMembersGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("PartitionsGuid", "UserMembersGuid");

                    b.HasIndex("UserMembersGuid");

                    b.ToTable("PartitionUser");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("PartitionUserHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("PartitionUserGroup", b =>
                {
                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGroupMembersGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("PartitionsGuid", "UserGroupMembersGuid");

                    b.HasIndex("UserGroupMembersGuid");

                    b.ToTable("PartitionUserGroup");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("PartitionUserGroupHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.Property<Guid>("UserGroupsGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.HasKey("UserGroupsGuid", "UsersGuid");

                    b.HasIndex("UsersGuid");

                    b.ToTable("UserUserGroup");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserUserGroupHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("ArticlePartition", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleMembersGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fargo.Core.Articles.Article", b =>
                {
                    b.OwnsOne("Fargo.Core.Articles.ArticleContainer", "Container", b1 =>
                        {
                            b1.Property<Guid>("ArticleGuid")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("MaxMass")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("ArticleGuid");

                            b1.ToTable("ArticleContainers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleGuid");
                        });

                    b.OwnsOne("Fargo.Core.Articles.ArticleKit", "Kit", b1 =>
                        {
                            b1.Property<Guid>("ArticleGuid")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ArticleGuid");

                            b1.ToTable("ArticleKits", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleGuid");

                            b1.OwnsMany("Fargo.Core.Articles.ArticleKitComponent", "Components", b2 =>
                                {
                                    b2.Property<Guid>("Guid")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ArticleGuid")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("FromArticleGuid");

                                    b2.Property<Guid>("KitArticleGuid")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Quantity")
                                        .HasColumnType("float");

                                    b2.HasKey("Guid");

                                    b2.HasIndex("ArticleGuid");

                                    b2.HasIndex("KitArticleGuid", "ArticleGuid")
                                        .IsUnique();

                                    b2.ToTable("ArticleKitPacks", (string)null);

                                    b2.HasOne("Fargo.Core.Articles.Article", "Article")
                                        .WithMany()
                                        .HasForeignKey("ArticleGuid")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("KitArticleGuid");

                                    b2.Navigation("Article");
                                });

                            b1.Navigation("Components");
                        });

                    b.OwnsOne("Fargo.Core.Articles.ArticlePack", "Pack", b1 =>
                        {
                            b1.Property<Guid>("ArticleGuid")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FromArticleGuid")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Quantity")
                                .HasColumnType("float");

                            b1.HasKey("ArticleGuid");

                            b1.HasIndex("FromArticleGuid");

                            b1.ToTable("ArticlePacks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleGuid");

                            b1.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                                .WithMany()
                                .HasForeignKey("FromArticleGuid")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("FromArticle");
                        });

                    b.OwnsOne("Fargo.Core.Articles.ArticleVariation", "Variation", b1 =>
                        {
                            b1.Property<Guid>("ArticleGuid")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("FromArticleGuid")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ArticleGuid");

                            b1.HasIndex("FromArticleGuid");

                            b1.ToTable("ArticleVariations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ArticleGuid");

                            b1.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                                .WithMany()
                                .HasForeignKey("FromArticleGuid")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.Navigation("FromArticle");
                        });

                    b.Navigation("Container");

                    b.Navigation("Kit");

                    b.Navigation("Pack");

                    b.Navigation("Variation");
                });

            modelBuilder.Entity("Fargo.Core.Identity.RefreshToken", b =>
                {
                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Fargo.Core.Items.ItemContainer", b =>
                {
                    b.HasOne("Fargo.Core.Items.Item", "Item")
                        .WithOne("Container")
                        .HasForeignKey("Fargo.Core.Items.ItemContainer", "ItemGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "ParentPartition")
                        .WithMany("PartitionMembers")
                        .HasForeignKey("ParentPartitionGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPartition");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPartitionAccess", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "Partition")
                        .WithMany()
                        .HasForeignKey("PartitionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.UserGroups.UserGroup", "UserGroup")
                        .WithMany("PartitionAccesses")
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partition");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPermission", b =>
                {
                    b.HasOne("Fargo.Core.UserGroups.UserGroup", "UserGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Fargo.Core.Users.UserPartitionAccess", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "Partition")
                        .WithMany()
                        .HasForeignKey("PartitionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Users.User", "User")
                        .WithMany("PartitionAccesses")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Fargo.Core.Users.UserPermission", b =>
                {
                    b.HasOne("Fargo.Core.Users.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItemPartition", b =>
                {
                    b.HasOne("Fargo.Core.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemMembersGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartitionUser", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserMembersGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartitionUserGroup", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.UserGroups.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupMembersGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.HasOne("Fargo.Core.UserGroups.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UsersGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.Navigation("Container");
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.Navigation("PartitionMembers");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.Navigation("PartitionAccesses");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Fargo.Core.Users.User", b =>
                {
                    b.Navigation("PartitionAccesses");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
