// <auto-generated />
using System;
using Fargo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fargo.Infrastructure.Migrations
{
    [DbContext(typeof(FargoDbContext))]
    partial class FargoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticlePartition", b =>
                {
                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uuid");

                    b.HasKey("ArticleGuid", "PartitionsGuid");

                    b.HasIndex("PartitionsGuid");

                    b.ToTable("ArticlePartition");
                });

            modelBuilder.Entity("Fargo.Core.Articles.Article", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArticleType")
                        .HasColumnType("integer");

                    b.Property<string>("Code128")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Code39")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("DataMatrix")
                        .HasMaxLength(2335)
                        .HasColumnType("character varying(2335)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ean13")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Ean8")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Gs1128")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Itf14")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("LengthX")
                        .HasColumnType("text");

                    b.Property<string>("LengthY")
                        .HasColumnType("text");

                    b.Property<string>("LengthZ")
                        .HasColumnType("text");

                    b.Property<string>("Mass")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QrCode")
                        .HasMaxLength(2953)
                        .HasColumnType("character varying(2953)");

                    b.Property<long?>("ShelfLife")
                        .HasColumnType("bigint");

                    b.Property<string>("UpcA")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("UpcE")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid?>("article_guid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("Code128")
                        .IsUnique()
                        .HasFilter("code128 IS NOT NULL");

                    b.HasIndex("Code39")
                        .IsUnique()
                        .HasFilter("code39 IS NOT NULL");

                    b.HasIndex("DataMatrix")
                        .IsUnique()
                        .HasFilter("data_matrix IS NOT NULL");

                    b.HasIndex("Ean13")
                        .IsUnique()
                        .HasFilter("ean13 IS NOT NULL");

                    b.HasIndex("Ean8")
                        .IsUnique()
                        .HasFilter("ean8 IS NOT NULL");

                    b.HasIndex("Gs1128")
                        .IsUnique()
                        .HasFilter("gs1128 IS NOT NULL");

                    b.HasIndex("Itf14")
                        .IsUnique()
                        .HasFilter("itf14 IS NOT NULL");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasFilter("qr_code IS NOT NULL");

                    b.HasIndex("UpcA")
                        .IsUnique()
                        .HasFilter("upc_a IS NOT NULL");

                    b.HasIndex("UpcE")
                        .IsUnique()
                        .HasFilter("upc_e IS NOT NULL");

                    b.HasIndex("article_guid")
                        .IsUnique();

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleContainer", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MaxMass")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("article_containers", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKit", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("article_kits", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKitComponent", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleKitGuid")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("Guid");

                    b.HasIndex("ArticleGuid");

                    b.HasIndex("ArticleKitGuid");

                    b.ToTable("article_kit_components", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticlePack", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromArticleGuid")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("Guid");

                    b.HasIndex("FromArticleGuid");

                    b.ToTable("article_packs", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleVariation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromArticleGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("FromArticleGuid");

                    b.ToTable("article_variations", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserGuid");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentContainerGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProductionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("article_guid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("ArticleGuid");

                    b.HasIndex("ParentContainerGuid");

                    b.HasIndex("article_guid")
                        .IsUnique();

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Items.ItemContainer", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("item_containers", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentPartitionGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserGroupGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("ParentPartitionGuid");

                    b.HasIndex("UserGroupGuid");

                    b.ToTable("partitions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nameid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Guid");

                    b.HasIndex("Nameid")
                        .IsUnique();

                    b.ToTable("user_groups", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPermission", b =>
                {
                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasAlternateKey("UserGroupGuid", "Action");

                    b.ToTable("user_group_permissions", (string)null);
                });

            modelBuilder.Entity("Fargo.Core.Users.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("DefaultPasswordExpirationPeriod")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nameid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("RequirePasswordChangeAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.HasIndex("Nameid")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ItemPartition", b =>
                {
                    b.Property<Guid>("ItemGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uuid");

                    b.HasKey("ItemGuid", "PartitionsGuid");

                    b.HasIndex("PartitionsGuid");

                    b.ToTable("ItemPartition");
                });

            modelBuilder.Entity("PartitionUser", b =>
                {
                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("PartitionsGuid", "UserGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("PartitionUser");
                });

            modelBuilder.Entity("PartitionUser1", b =>
                {
                    b.Property<Guid>("PartitionAccessesGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User1Guid")
                        .HasColumnType("uuid");

                    b.HasKey("PartitionAccessesGuid", "User1Guid");

                    b.HasIndex("User1Guid");

                    b.ToTable("PartitionUser1");
                });

            modelBuilder.Entity("PartitionUserGroup", b =>
                {
                    b.Property<Guid>("PartitionsGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGroupGuid")
                        .HasColumnType("uuid");

                    b.HasKey("PartitionsGuid", "UserGroupGuid");

                    b.HasIndex("UserGroupGuid");

                    b.ToTable("PartitionUserGroup");
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.Property<Guid>("UserGroupsGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uuid");

                    b.HasKey("UserGroupsGuid", "UserGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("UserUserGroup");
                });

            modelBuilder.Entity("ArticlePartition", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", null)
                        .WithMany()
                        .HasForeignKey("ArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fargo.Core.Articles.Article", b =>
                {
                    b.HasOne("Fargo.Core.Articles.ArticleContainer", "Container")
                        .WithOne()
                        .HasForeignKey("Fargo.Core.Articles.Article", "article_guid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fargo.Core.Articles.ArticleKit", "Kit")
                        .WithOne()
                        .HasForeignKey("Fargo.Core.Articles.Article", "article_guid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fargo.Core.Articles.ArticlePack", "Pack")
                        .WithOne()
                        .HasForeignKey("Fargo.Core.Articles.Article", "article_guid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fargo.Core.Articles.ArticleVariation", "Variation")
                        .WithOne()
                        .HasForeignKey("Fargo.Core.Articles.Article", "article_guid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Container");

                    b.Navigation("Kit");

                    b.Navigation("Pack");

                    b.Navigation("Variation");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKitComponent", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Articles.ArticleKit", null)
                        .WithMany("Components")
                        .HasForeignKey("ArticleKitGuid");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticlePack", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                        .WithMany()
                        .HasForeignKey("FromArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromArticle");
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleVariation", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "FromArticle")
                        .WithMany()
                        .HasForeignKey("FromArticleGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromArticle");
                });

            modelBuilder.Entity("Fargo.Core.Identity.RefreshToken", b =>
                {
                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fargo.Core.Items.Item", b =>
                {
                    b.HasOne("Fargo.Core.Articles.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Items.Item", "ParentContainer")
                        .WithMany()
                        .HasForeignKey("ParentContainerGuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fargo.Core.Items.ItemContainer", "Container")
                        .WithOne()
                        .HasForeignKey("Fargo.Core.Items.Item", "article_guid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("Container");

                    b.Navigation("ParentContainer");
                });

            modelBuilder.Entity("Fargo.Core.Partitions.Partition", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", "ParentPartition")
                        .WithMany()
                        .HasForeignKey("ParentPartitionGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fargo.Core.UserGroups.UserGroup", null)
                        .WithMany("PartitionAccesses")
                        .HasForeignKey("UserGroupGuid");

                    b.Navigation("ParentPartition");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroupPermission", b =>
                {
                    b.HasOne("Fargo.Core.UserGroups.UserGroup", "UserGroup")
                        .WithMany("Permissions")
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("ItemPartition", b =>
                {
                    b.HasOne("Fargo.Core.Items.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartitionUser", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartitionUser1", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionAccessesGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("User1Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartitionUserGroup", b =>
                {
                    b.HasOne("Fargo.Core.Partitions.Partition", null)
                        .WithMany()
                        .HasForeignKey("PartitionsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.UserGroups.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserUserGroup", b =>
                {
                    b.HasOne("Fargo.Core.UserGroups.UserGroup", null)
                        .WithMany()
                        .HasForeignKey("UserGroupsGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fargo.Core.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fargo.Core.Articles.ArticleKit", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Fargo.Core.UserGroups.UserGroup", b =>
                {
                    b.Navigation("PartitionAccesses");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
