<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="UnitsNet" Version="5.75.1" />
        <PackageReference Include="UnitsNet.NumberExtensions" Version="5.75.1" />
    </ItemGroup>

</Project>
