namespace Fargo.Sdk.Contracts.Errors;

/// <summary>
/// Represents an RFC 7807 problem details response from the Fargo API.
/// </summary>
public sealed class FargoProblemDetails
{
    /// <summary>Gets a machine-readable identifier for the problem type.</summary>
    public string? Type { get; init; }

    /// <summary>Gets a short human-readable summary of the problem.</summary>
    public string? Title { get; init; }

    /// <summary>Gets a human-readable explanation specific to this occurrence.</summary>
    public string? Detail { get; init; }

    /// <summary>Gets the HTTP status code generated by the origin server.</summary>
    public int? Status { get; init; }

    /// <summary>Gets a URI reference that identifies the specific occurrence.</summary>
    public string? Instance { get; init; }

    /// <summary>Gets the backend trace identifier associated with this occurrence.</summary>
    public string? TraceId { get; init; }
}
